### ISSUE TITLE
The plugin cannot be easily disabled

### ISSUE THREAD

**Issue by JustBlackBird** [Mibew/button-refresh-plugin#1]
The button needs to be regenerated after the plugin becomes disabled/uninstalled to stop the refreshing. Also after changing plugin's settings the button needs to be regenerated too.

I believe there is another way to interact with the core that does not need the button to be regenerated at every change.

**Comment by faf** [comment]
Implemented in [this plugin](https://github.com/Mibew/advanced-button-plugin).
